# Binary Sensors
# Add your binary sensors here

# Example: Template binary sensors
- platform: template
  sensors:
    workday:
      friendly_name: "Workday"
      value_template: >
        {{ is_state('binary_sensor.workday_sensor', 'on') }}
      device_class: occupancy

# Example: Ping binary sensor
- platform: ping
  host: 8.8.8.8
  name: "Internet Connection"
  count: 2
  scan_interval: 30
