# Home Assistant Configuration
# https://www.home-assistant.io/docs/configuration/

# Basic Configuration
homeassistant:
  name: Home
  latitude: -34.9285
  longitude: 138.6007
  elevation: 50
  unit_system: metric
  time_zone: Australia/Adelaide
  country: AU
  currency: AUD

# Default Configuration - includes most basic integrations
default_config:

# HTTP Configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 10.0.0.0/8
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Logger Configuration
logger:
  default: info
  logs:
    homeassistant.core: info
    homeassistant.components.http: warning
