# Lights
# Add your lights here

# Example: Template lights
- platform: template
  lights:
    example_light:
      friendly_name: "Example Light"
      value_template: "{{ is_state('switch.example_switch', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.example_switch
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.example_switch
