version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin
    network_mode: host
    volumes:
      - ${VOLUME1}
      - ${VOLUME2}
      - type: bind
        source: ${BIND1SOURCE}
        target: ${BIND1TARGET}
      - type: bind
        source: ${BIND2SOURCE}
        target: ${BIND2TARGET}
    environment:
      - JELLYFIN_PublishedServerUrl=${PUBLISHED}
    restart: unless-stopped
