version: "3.8"

services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    environment:
      - LOG_LEVEL=debug
      - TZ=${TZ}
    volumes:
      - jellyseerr_config_v1:/app/config
    networks:
      - dokploy-network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.cooked.beer`)"
        - "traefik.http.routers.jellyseerr.entrypoints=web"
        - "traefik.http.routers.jellyseerr.tls=false"
        - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"
        - "traefik.docker.network=dokploy-network"

volumes:
  jellyseerr_config_v1:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.184,nfsvers=4.1,rw"
      device: ":/export/appdata/jellyseerr/config"

networks:
  dokploy-network:
    external: true
