version: '3'
services:
    jellyseerr:
       image: fallenbagel/jellyseerr:latest
       container_name: jellyseerr
       environment:
            - LOG_LEVEL=debug
            - TZ=${TZ}
       ports:
            - ${PORT}
       volumes:
            - /path/to/appdata/config:/app/config
       restart: unless-stopped
