version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    network_mode: host
    environment:
      - JELLYFIN_PublishedServerUrl=https://metal0.risk-lenok.ts.net
      - TZ=Australia/Adelaide
    volumes:
      - jellyfin_config_v2:/config                 # NFS (Rockstor)
      - jellyfin_cache_v2:/cache                   # NFS (Rockstor)
      - jellyfin_db_local:/config/data             # LOCAL tiny DB overlay (fixes locks)
      - type: tmpfs                                # super fast transcode scratch
        target: /transcode
        tmpfs:
          size: 8g
      - plex_media_v1:/media/plex                  # NAS #2 share root
      - emby_media_v1:/media/emby                  # NAS #1 share root
    deploy:
      placement:
        constraints:
          - node.hostname == metal0                # keep Jellyfin on metal0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  # Rockstor (config + cache)
  jellyfin_config_v2:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.184,nfsvers=4.1,rw
      device: :/export/appdata/jellyfin/config

  jellyfin_cache_v2:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.184,nfsvers=4.1,rw
      device: :/export/appdata/jellyfin/cache

  # LOCAL ONLY (on metal0) – tiny footprint, solves SQLite locks
  jellyfin_db_local:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/jellyfin-db

  # Media (Synology shares)
  plex_media_v1:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.154,nfsvers=3,rw
      device: ":/volume1/Plex Media"

  emby_media_v1:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.153,nfsvers=3,rw
      device: :/volume1/emby_media
