version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin
    network_mode: host
    volumes:
      - /srv/appdata/jellyfin/config:/config
      - /srv/appdata/jellyfin/cache:/cache
      - type: bind
        source: /srv/media/plex
        target: /media/plex
      - type: bind
        source: /srv/media/emby
        target: /media/emby
    environment:
      - JELLYFIN_PublishedServerUrl=https://metal0.risk-lenok.ts.net
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == metal0  # Funnel will only run from this node
