version: "3.8"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
    volumes:
      - /srv/appdata/prowlarr/config:/config
    networks:
      - dokploy-network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.cooked.beer`)"
        - "traefik.http.routers.prowlarr.entrypoints=web"
        - "traefik.http.routers.prowlarr.tls=false"
        - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
        - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true
