version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /srv/appdata/radarr/config:/app/config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.radarr.rule=Host(`radarr.cooked.beer`)"
        - "traefik.http.routers.radarr.entrypoints=websecure"
        - "traefik.http.routers.radarr.tls.certresolver=letsencrypt"
        - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
        - dokploy-network
networks:
  dokploy-network:
    external: true