version: "3.8"

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
    volumes:
      - /srv/appdata/radarr/config:/config
    networks:
      - dokploy-network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.radarr.rule=Host(`radarr.cooked.beer`)"
        - "traefik.http.routers.radarr.entrypoints=web"
        - "traefik.http.routers.radarr.tls=false"
        - "traefik.http.services.radarr.loadbalancer.server.port=7878"
        - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true
