version: "3.8"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /srv/appdata/radarr/config:/app/config
    ports:
      - ${PORTS}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure