version: "3.8"

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
      - HOST_WHITELIST=${HOST}
    volumes:
      - sabnzbd_config_v2:/config
      - downloads_v4:/downloads
    networks:
      - dokploy-network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.cooked.beer`)"
        - "traefik.http.routers.sabnzbd.entrypoints=web"
        - "traefik.http.routers.sabnzbd.tls=false"
        - "traefik.http.services.sabnzbd.loadbalancer.server.port=8080"
        - "traefik.docker.network=dokploy-network"
        - "diun.enable=true"

volumes:
  sabnzbd_config_v2:
    driver: local
    driver_opts:
      type: "nfs"               # keep as nfs; v3/v4 decided by options
      o: "addr=192.168.1.184,nfsvers=4.1,rw"
      device: ":/export/appdata/sabnzbd/config"

  downloads_v4:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.154,vers=3,rw"
      device: ":/volume1/Plex Media"

networks:
  dokploy-network:
    external: true
