version: "3.8"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Adelaide
    volumes:
      - sonarr_config:/config
      - /srv/media/plex/TV shows:/tv
      - /srv/media/plex/Downloads:/downloads
    networks:
      - dokploy-network
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sonarr.rule=Host(`sonarr.cooked.beer`)"
        - "traefik.http.routers.sonarr.entrypoints=web"
        - "traefik.http.routers.sonarr.tls=false"
        - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
        - "traefik.docker.network=dokploy-network"

volumes:
  sonarr_config:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.184,nfsvers=4.1,rw"
      device: ":/export/appdata/sonarr/config"

networks:
  dokploy-network:
    external: true
