# Traefik dynamic configuration for Kubero services
# Place this file in: /etc/dokploy/traefik/dynamic/kubero.yml
# Cloudflare handles SSL termination, so we only need HTTPS routes

http:
  routers:
    # Kubero UI - Accept HTTPS from Cloudflare, send HTTP to k3s
    kubero-ui:
      rule: "Host(`kubero.cooked.beer`)"
      service: kubero-service
      entryPoints:
        - websecure
      # No TLS config needed - Cloudflare handles it

    # Kubero Registry - Accept HTTPS from Cloudflare, send HTTP to k3s
    kubero-registry:
      rule: "Host(`registry.kubero.cooked.beer`)"
      service: kubero-service
      entryPoints:
        - websecure
      # No TLS config needed - Cloudflare handles it

  services:
    # Service pointing to k3s NGINX ingress (HTTP only, no TLS)
    kubero-service:
      loadBalancer:
        servers:
          - url: "http://192.168.1.190:30665"
        healthCheck:
          path: "/"
          interval: "30s"
          timeout: "5s"
