services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
     - ${PORT}
    volumes:
     - ./bitwarden:/data:rw
    environment:
#     - ROCKET_TLS={certs="/ssl/certs/certs.pem",key="/ssl/private/key.pem"}  // Environment variable is specific to the Rocket web server
     - ADMIN_TOKEN=$$argon2id$$v=19$$m=65540,t=3,p=4$$ak00RFBPT3VjMG1pYUhFdHREOUkwbGNpYzJKbzBlSmJhZHNEckcrR3c2MD0$$cq5qUwl8+0ImM+g3DzxR1J0zC8XxDyC8JlSU4LB4be8
     - WEBSOCKET_ENABLED=false
     - SIGNUPS_ALLOWED=false
     - INVITATIONS_ALLOWED=true
     - DOMAIN=${DOMAIN}