version: "3.8"

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    environment:
      - TZ=Australia/Adelaide
    volumes:
      - ha_config_v1:/config
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == metal4
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
      rollback_config:
        order: stop-first
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8123/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  ha-edge:
    image: nginx:alpine
    networks:
      - dokploy-network
    environment:
      # MUST point to the LAN IP:port of the HA host-node (yours is metal4)
      - HA_UPSTREAM=192.168.1.194:8123
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=dokploy-network"
        - "traefik.http.routers.ha.rule=Host(`assistant.cooked.beer`)"
        - "traefik.http.routers.ha.entrypoints=web"
        - "traefik.http.routers.ha.tls=false"
        # nginx will listen on 8080, so Traefik should target 8080
        - "traefik.http.services.ha.loadbalancer.server.port=8080"
    command:
      - /bin/sh
      - -lc
      - |
        apk add --no-cache gettext >/dev/null 2>&1
        : "${HA_UPSTREAM:?Set HA_UPSTREAM to e.g. 192.168.1.194:8123}"

        cat >/etc/nginx/conf.d/default.conf.template <<'EOT'
        map $http_upgrade $connection_upgrade {
          default close;
          websocket upgrade;
          Upgrade upgrade;
        }
        server {
          listen 8080;

          location / {
            proxy_pass http://$HA_UPSTREAM;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
          }
        }
        EOT

        # Only substitute HA_UPSTREAM to avoid touching $host, $remote_addr etc.
        envsubst '${HA_UPSTREAM}' </etc/nginx/conf.d/default.conf.template >/etc/nginx/conf.d/default.conf
        echo "Using HA_UPSTREAM=${HA_UPSTREAM}"
        exec nginx -g 'daemon off;'

volumes:
  ha_config_v1:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.184,nfsvers=4.1,rw
      device: :/export/appdata/homeassistant/config

networks:
  dokploy-network:
    external: true
