version: "3.8"

services:
  # --- Home Assistant: host net for discovery ---
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    network_mode: host
    environment:
      - TZ=Australia/Adelaide
    volumes:
      - ha_config_v1:/config
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          # Keep HA on metal4 so the sidecar can always reach it by LAN IP
          - node.hostname == metal4
      restart_policy:
        condition: on-failure
      update_config:
        order: stop-first
      rollback_config:
        order: stop-first
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8123/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # --- HA "edge" sidecar: lives on Traefik overlay and forwards to HA on metal4:8123 ---
  ha-edge:
    image: nginx:alpine
    networks:
      - dokploy-network
    environment:
      # Upstream is the HA node LAN IP:port (since HA is in host networking)
      - UPSTREAM=192.168.1.194:8123
    deploy:
      replicas: 1
      placement:
        - node.hostname == metal4   # optional but keeps traffic local
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=dokploy-network"

        # Router
        - "traefik.http.routers.ha.rule=Host(`assistant.cooked.beer`)"
        - "traefik.http.routers.ha.entrypoints=web"
        - "traefik.http.routers.ha.tls=false"

        # Service points to this container's port 8080 (matches nginx listen)
        - "traefik.http.services.ha.loadbalancer.server.port=8080"
    command:
      - /bin/sh
      - -lc
      - |
        apk add --no-cache gettext >/dev/null 2>&1
        cat >/etc/nginx/conf.d/default.conf.template <<'EOT'
        server {
          listen 8080;
          # allow large uploads/backups if needed
          client_max_body_size 0;

          location / {
            proxy_pass http://$UPSTREAM;
            proxy_http_version 1.1;

            # Preserve client info for Home Assistant
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket upgrade
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            # Timeouts for long-lived streams
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;
          }
        }
        EOT
        envsubst '$UPSTREAM' </etc/nginx/conf.d/default.conf.template >/etc/nginx/conf.d/default.conf
        exec nginx -g 'daemon off;'

volumes:
  ha_config_v1:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.1.184,nfsvers=4.1,rw
      device: :/export/appdata/homeassistant/config

networks:
  dokploy-network:
    external: true
