services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - monitor
    deploy:
      placement:
        constraints: [node.hostname != metal0]  # Run on worker nodes only
      resources:
        limits:
          cpus: '3.0'
          memory: 2048M
        reservations:
          cpus: '1.0'
          memory: 1024M

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
      - NODE_OPTIONS=--max-old-space-size=1536
    volumes:
      - ./elk/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    ports:
      - "5601:5601"
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints: [node.hostname != metal0]  # Run on worker nodes only
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kibana.rule=Host(`cluster.cooked.beer`)"
        - "traefik.http.routers.kibana.entrypoints=websecure"
        - "traefik.http.services.kibana.loadbalancer.server.port=5601"
        - "traefik.http.routers.kibana.tls.certresolver=myresolver"

  # Metricbeat - Only on worker nodes to minimize impact on Jellyfin
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.15.1
    user: root
    command: metricbeat -e -strict.perms=false
    volumes:
      - ./elk/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
          - node.hostname != metal0  # Exclude Jellyfin node
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  # Filebeat - Only on worker nodes to minimize impact on Jellyfin
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.1
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./elk/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
          - node.hostname != metal0  # Exclude Jellyfin node
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  # Optional: Lightweight monitoring for metal0 only if needed
  metricbeat-jellyfin-node:
    image: docker.elastic.co/beats/metricbeat:8.15.1
    user: root
    command: metricbeat -e -strict.perms=false
    volumes:
      - ./elk/metricbeat-minimal.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      replicas: 0  # Disabled by default - enable only if needed
      placement:
        constraints:
          - node.hostname == metal0
      resources:
        limits:
          cpus: '0.1'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

  elastalert:
    image: jertel/elastalert2:latest
    volumes:
      - ./elk/elastalert:/opt/elastalert/rules
      - ./elk/elastalert.yml:/opt/elastalert/config.yaml:ro
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints: [node.hostname != metal0]  # Run on worker nodes only
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

volumes:
  elasticsearch_data:

networks:
  monitor:
    driver: overlay
