services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - monitor
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M
        reservations:
          cpus: '0.5'
          memory: 512M

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kibana.rule=Host(`cluster.cooked.beer`)"
        - "traefik.http.routers.kibana.entrypoints=websecure"
        - "traefik.http.services.kibana.loadbalancer.server.port=5601"
        - "traefik.http.routers.kibana.tls.certresolver=myresolver"

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.15.1
    user: root
    command: metricbeat -e -strict.perms=false
    volumes:
      - ./elk/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.1
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./elk/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux

  elastalert:
    image: jertel/elastalert2:latest
    volumes:
      - ./elk/elastalert:/opt/elastalert/rules
      - ./elk/elastalert.yml:/opt/elastalert/config.yaml:ro
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.2'
          memory: 128M

volumes:
  elasticsearch_data:

networks:
  monitor:
    driver: overlay
