services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - monitor
    deploy:
      placement:
        constraints: [node.hostname != metal0]  # Run on worker nodes only
      resources:
        limits:
          cpus: '3.0'
          memory: 2048M
        reservations:
          cpus: '1.0'
          memory: 1024M

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
      - NODE_OPTIONS=--max-old-space-size=1536
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
      - LOGGING_ROOT_LEVEL=warn
    ports:
      - "5601:5601"
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints: [node.hostname != metal0]  # Run on worker nodes only
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
        reservations:
          cpus: '0.5'
          memory: 1024M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.kibana.rule=Host(`cluster.cooked.beer`)"
        - "traefik.http.routers.kibana.entrypoints=websecure"
        - "traefik.http.services.kibana.loadbalancer.server.port=5601"
        - "traefik.http.routers.kibana.tls.certresolver=myresolver"

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.15.1
    user: root
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - KIBANA_HOST=kibana:5601
    command: >
      bash -c "
      cat > /usr/share/metricbeat/metricbeat.yml <<EOF
      metricbeat.modules:
      - module: system
        metricsets: [cpu, load, memory, network, process, process_summary, socket_summary, filesystem, diskio]
        enabled: true
        period: 10s
        processes: ['.*']
        cpu.metrics: [percentages, normalized_percentages]
        core.metrics: [percentages]
      - module: docker
        metricsets: [container, cpu, diskio, healthcheck, info, memory, network]
        hosts: [unix:///var/run/docker.sock]
        period: 10s
        enabled: true
      processors:
      - add_host_metadata:
          when.not.contains.tags: forwarded
      - add_docker_metadata: ~
      output.elasticsearch:
        hosts: ['elasticsearch:9200']
      setup.template.settings:
        index.number_of_shards: 1
        index.codec: best_compression
      setup.kibana:
        host: kibana:5601
      logging.level: info
      EOF
      metricbeat -e -strict.perms=false
      "
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.1
    user: root
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - KIBANA_HOST=kibana:5601
    command: >
      bash -c "
      cat > /usr/share/filebeat/filebeat.yml <<EOF
      filebeat.inputs:
      - type: container
        paths:
          - '/var/lib/docker/containers/*/*.log'
        processors:
        - add_docker_metadata:
            host: unix:///var/run/docker.sock
      processors:
      - add_host_metadata:
          when.not.contains.tags: forwarded
      output.elasticsearch:
        hosts: ['elasticsearch:9200']
      setup.template.settings:
        index.number_of_shards: 1
        index.codec: best_compression
      setup.kibana:
        host: kibana:5601
      logging.level: info
      EOF
      filebeat -e -strict.perms=false
      "
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

  elastalert:
    image: jertel/elastalert2:latest
    volumes:
      - ./elk/elastalert:/opt/elastalert/rules
      - ./elk/elastalert.yml:/opt/elastalert/config.yaml:ro
    networks:
      - monitor
    depends_on:
      - elasticsearch
    deploy:
      placement:
        constraints: [node.hostname != metal0]  # Run on worker nodes only
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

volumes:
  elasticsearch_data:

networks:
  monitor:
    driver: overlay
