metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - filesystem
    - diskio
  enabled: true
  period: 30s
  processes: ['.*']

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 30s
  enabled: true

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~

output.elasticsearch:
  hosts: ['elasticsearch:9200']

setup.kibana:
  host: "kibana:5601"

logging.level: warning
