metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# Minimal monitoring for Jellyfin node - only essential metrics
metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - memory
    - filesystem
  enabled: true
  period: 30s  # Less frequent collection
  cpu.metrics: ["percentages"]

# Monitor only Jellyfin container specifically
- module: docker
  metricsets:
    - container
    - memory
    - cpu
  hosts: ["unix:///var/run/docker.sock"]
  period: 30s  # Less frequent collection
  enabled: true
  # Only monitor Jellyfin container
  containers.ids: ["jellyfin*"]

processors:
- add_host_metadata:
    when.not.contains.tags: forwarded
- add_docker_metadata: ~

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  index: "metricbeat-jellyfin-%{+yyyy.MM.dd}"

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:
  host: "kibana:5601"

logging.level: warning  # Reduce logging
logging.to_files: true
logging.files:
  path: /var/log/metricbeat
  name: metricbeat
  keepfiles: 3  # Keep fewer log files
  permissions: 0644
