global:
  resolve_timeout: 5m

route:
  receiver: 'teams-webhook'
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'teams-webhook'
    webhook_configs:
      - url: 'http://prometheus-msteams:2000/alertmanager'
        send_resolved: true