global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - '192.168.1.190:9100'
          - '192.168.1.191:9100'
          - '192.168.1.192:9100'
        labels:
          cluster: 'main'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - '192.168.1.190:8085'
          - '192.168.1.191:8085'
          - '192.168.1.192:8085'
        labels:
          cluster: 'main'

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
