global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 'metal0:9100'
          - 'metal1:9100'
          - 'metal2:9100'
        labels:
          cluster: 'main'

  - job_name: 'cadvisor'
    static_configs:
      - targets:
          - 'metal0:8080'
          - 'metal1:8080'
          - 'metal2:8080'
        labels:
          cluster: 'main'

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
